[profile.default]
emv_version = "paris"
src = "src"
out = "out"
script = "script"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]
remappings = [
  "@ERC4337/=node_modules/@ERC4337/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@prb/math/=node_modules/@prb/math/src/",
  "@rhinestone/=node_modules/@rhinestone/",
  "@safe-global/=node_modules/@safe-global/",
  "@semaphore-protocol/=node_modules/@semaphore-protocol/contracts/",
  "account-abstraction-v0.6/=node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
  "account-abstraction/=node_modules/@ERC4337/account-abstraction/contracts/",
  "ds-test/=node_modules/ds-test/src/",
  "erc4337-validation/=node_modules/@rhinestone/erc4337-validation/src/",
  "erc7579/=node_modules/erc7579/src/",
  "ExcessivelySafeCall/=node_modules/excessively-safe-call/src/",
  "forge-std/=node_modules/forge-std/src/",
  "kernel/=node_modules/@zerodev/kernel/src/",
  "module-bases/=node_modules/@rhinestone/module-bases/src/",
  "modulekit/=node_modules/@rhinestone/modulekit/src/",
  "safe7579/=node_modules/@rhinestone/safe7579/src/",
  "sentinellist/=node_modules/@rhinestone/sentinellist/src/",
  "solady/=node_modules/solady/src/",
  "solarray/=node_modules/solarray/src/"
]

# For simulation: https://docs.rhinestone.wtf/modulekit/testing/simulation
gas_limit = "18446744073709551615"
memory_limit = 2147483648
verbosity = 3

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
